### ISSUE TITLE
Uncss can not remove duplicate style !!! Please improve it

### ISSUE THREAD

**Issue by lovezhuoyang** [pajasevi/UnCSS-Online#7]
I tried to get html and css fragments of the page through firebug, so it will produce a lot of duplicate css class。
so Please improve it
thax

**Comment by simi** [comment]
Hello! Can you post steps how to reproduce this? What's input, what's output and what's expected?

**Comment by Riz-waan** [comment]
So what is happening is that if you enter this into the HTML place:

`<p class='hi'>This is the p attribute</p>` 

And this into the CSS tag:
```

.hi {
color: blue;
background-color: green;
color: blue;
}

.hi {
color: blue;
background-color: green;
color: blue;
}
```


You get this as the output:

```
.hi {
color: blue;
background-color: green;
color: blue;
}

.hi {
color: blue;
background-color: green;
color: blue;
}
```


He is wanting you to improve the program in order to output it like this instead:

```
.hi {
color: blue;
background-color: green;
}
```

Because the rest is just duplicate.

Thanks,
Rizwaan

**Comment by RyanZim** [comment]
That's outside of the scope of uncss; use http://cssnano.co/ for that.

**Comment by pajasevi** [comment]
@RyanZim is right. It's outside of the scope. And even if it was, this service just uses UnCSS library - the improvement would have to be there.
